[settings.host-containers.admin]
enabled = true
superpowered = true
source = "public.ecr.aws/bottlerocket/bottlerocket-admin:v0.7.2"

[settings.host-containers.control]
enabled = true
superpowered = false
source = "public.ecr.aws/bottlerocket/bottlerocket-control:v0.5.2"
